{{- if .Values.servicemonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: {{ include "helm-static_application.fullname" . }}
    {{- range $key, $val := .Values.servicemonitor.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
    {{- range $key, $val := .Values.commonlabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: {{ include "helm-static_application.fullname" . }}
spec:
  endpoints:
  - interval: {{ .Values.servicemonitor.endpoints.interval }}
    port: {{ .Values.servicemonitor.endpoints.port }}
    #tolower 
    scheme: {{ .Values.servicemonitor.endpoints.scheme | lower }}
    path: {{ .Values.servicemonitor.endpoints.path }}
  selector:
    matchLabels:
      {{- include "helm-static_application.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{.Release.Namespace}}
{{- end }}
